# permissions for end users to view knotoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: knotoperator-viewer-role
rules:
- apiGroups:
  - cache.knotfree.net
  resources:
  - knotoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.knotfree.net
  resources:
  - knotoperators/status
  verbs:
  - get
