
# see: https://cert-manager.io/docs/configuration/acme/dns01/google/
# and: https://cert-manager.io/docs/configuration/acme/dns01


apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: knotfree
  namespace: cert-manager # knotspace
spec:
  secretName: knotfree-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "knotfree.net" # knotfree.05548fc2-4953-4209-8299-1241cab85e16.lb.civo.com
  dnsNames:
  - "knotfree.net"   
  - "*.knotfree.net"   

