# Copyright 2019,2020 Alan Tracey Wootton 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "aide"
  labels:
    app: "knotfreeaide"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "knotfreeaide"
  template:
    metadata:
      labels:
        run: "knotfreeaide"
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9102'
    spec:
      containers:
      - name: golang
        imagePullPolicy: Always
        image: gcr.io/fair-theater-238820/knotfreeserver 
        command: ["/go/bin/linux_386/knotfreeiot"] 
        args: ["--server"] # ,"--nano"
        ports:
        - containerPort: 8384
          name : iot
        - containerPort: 1883
          name : mqtt
        - containerPort: 8080 
          name : http
        - containerPort: 8085 
          name : http-public
        - containerPort: 7465 
          name : text
        - containerPort: 3000 
          name : graf
        - containerPort: 9090 
          name : promfwd
        - containerPort: 8000 
          name : libra
        - containerPort: 9102 
          name : prom
        resources:
          limits:
            cpu: 250m  #INSERT_CPU_NEEDED_HERE
            memory: 800Mi #INSERT_MEM_NEEDED_HERE
          #requests:
            #cpu: 250m  #INSERT_CPU_NEEDED_HERE
            #memory: 800Mi #INSERT_MEM_NEEDED_HERE
        env:
        - name: NAME
          value: "knotfreeaide"
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: foo
          mountPath: "/root/atw/"
          readOnly: true
      volumes:
      - name: foo
        secret:
          secretName: privatekeys4
              
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: "knotfreeaide"
  name: "knotfreeaide"
  annotations:
    team: "knotfree"
spec:
  type: LoadBalancer
  ports:

  - port: 1883
    name: mqtt
    protocol: TCP
    
  - port: 7465
    name: text
    protocol: TCP

  - port: 8384
    name: iot
    protocol: TCP

  - name: http
    port: 80
    targetPort: 8085
    protocol: TCP

  - name: promfwd
    port: 9090
    targetPort: 9090 
    protocol: TCP

  - name: prom
    port: 9102
    targetPort: 9102 
    protocol: TCP

  - name: graf
    port: 3000
    targetPort: 3000
    protocol: TCP 

  - name: libra
    port: 8000
    targetPort: 8000
    protocol: TCP 

  selector:
    run: "knotfreeaide"

--- 


apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: knotfreeaide
  labels:
    team: knotfree
spec:
  selector:
    matchLabels:
      app: knotfreeaide
  endpoints:
  - port: prom

--- 

  # required
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: knotfree
  resources:
    requests:
      memory: 200Mi