kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knotoperator
subjects:
- kind: ServiceAccount
  name: knotoperator
roleRef:
  kind: Role
  name: knotoperator
  apiGroup: rbac.authorization.k8s.io
